// Generated by `dentmatmech export-browser`; do not edit.
window.DENTMATMECH_DATA = [
 {
  "name": "3Y-TZP zirconia ceramic",
  "slug": "3Y-TZP_Zirconia_Ceramic",
  "page_url": "../pages/materials/3Y-TZP_Zirconia_Ceramic.html",
  "description": "A zirconia polycrystalline ceramic dental restoration material that contains the first generation of dental zirconia fully stabilized with yttria (Y2O3) which are chiefly composed of the tetragonal phase (tetragonal zirconia polycrystals : TZPs) and are stabilized at room temperature with the addition of 3 mol% of yttrium oxide (3Y-TZP).",
  "term_id": "OHD:0001035",
  "term_label": "3Y-TZP zirconia ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Zirconia polycrystalline ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "4Y-PSZ zirconia ceramic",
  "slug": "4Y-PSZ_Zirconia_Ceramic",
  "page_url": "../pages/materials/4Y-PSZ_Zirconia_Ceramic.html",
  "description": "A zirconia polycrystalline ceramic dental restoration material that contains the next generation of dental zirconia with the addition of transparent, non-birefringent, cubic-phase stabilized with higher yttrium oxide (of approximately 25% of the cubic phase achieved with 4 mol% of yttrium oxide) with increased translucency in relation to 3Y-TZP for monolithic applications.",
  "term_id": "OHD:0001036",
  "term_label": "4Y-PSZ zirconia ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Zirconia polycrystalline ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "5Y-PSZ zirconia ceramic",
  "slug": "5Y-PSZ_Zirconia_Ceramic",
  "page_url": "../pages/materials/5Y-PSZ_Zirconia_Ceramic.html",
  "description": "A zirconia polycrystalline ceramic dental restoration material that contains zirconia with increased yttrium oxide (5-8% mol)",
  "term_id": "OHD:0001037",
  "term_label": "5Y-PSZ zirconia ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Zirconia polycrystalline ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Acid-base cement",
  "slug": "Acid-base_Cement",
  "page_url": "../pages/materials/Acid-base_Cement.html",
  "description": "A dental restoration material containing acid and liquid components in powder liquid form.",
  "term_id": "OHD:0001021",
  "term_label": "acid-base cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "STUB",
  "parents": [
   "Dental restoration material"
  ],
  "children": [
   "Glass ionomer cement",
   "Metal modified glass ionomer",
   "Resin-modified glass ionomer",
   "Zinc oxide cement",
   "Zinc phosphate cement",
   "Zinc polycarboxylate cement"
  ],
  "synonyms": [],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Alumina toughened zirconia ceramic",
  "slug": "Alumina_Toughened_Zirconia_Ceramic",
  "page_url": "../pages/materials/Alumina_Toughened_Zirconia_Ceramic.html",
  "description": "A polycrystalline composite ceramic dental restoration material that combine alumina to increase materials strength and toughness.",
  "term_id": "OHD:0001046",
  "term_label": "alumina toughened zirconia ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Polycrystalline composite ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Amalgam",
  "slug": "Amalgam",
  "page_url": "../pages/materials/Amalgam.html",
  "description": "A metal dental restoration material that consists of alloy that is formed by reacting mercury with silver, copper, tin and sometimes palladium, zinc and other elements to improve handling characteristics and clinical performance.",
  "term_id": "OHD:0000001",
  "term_label": "amalgam dental restoration material",
  "category": "METAL",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Metal"
  ],
  "children": [],
  "synonyms": [
   "dental amalgam",
   "silver filling",
   "silver amalgam"
  ],
  "setting_mechanisms": [
   "AMALGAMATION"
  ],
  "use_contexts": [
   "DIRECT_RESTORATION"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 6,
  "n_composition": 4,
  "n_properties": 0,
  "n_adverse_effects": 2,
  "fda_device_classes": [
   "CLASS_II"
  ],
  "fda_regulations": [
   "872.3070"
  ],
  "fda_product_codes": [
   "EJJ",
   "ELY",
   "OIV"
  ],
  "fda_statuses": [
   "CLEARED"
  ]
 },
 {
  "name": "Bulk-filled resin-based composite",
  "slug": "Bulk-filled_Resin-based_Composite",
  "page_url": "../pages/materials/Bulk-filled_Resin-based_Composite.html",
  "description": "A resin-based composite dental restoration material that enables the restoration to be built up in thick layers of up to 4 mm and are recommended by manufacturers to simplify clinical technique and save time compared to traditional incremental placement.",
  "term_id": "OHD:0001011",
  "term_label": "bulk-filled resin-based composite dental restoration material",
  "category": "RESIN_COMPOSITE",
  "curation_status": "STUB",
  "parents": [
   "Resin-based composite"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Calcium aluminate glass ionomer hybrid cement",
  "slug": "Calcium_Aluminate_Glass_Ionomer_Hybrid_Cement",
  "page_url": "../pages/materials/Calcium_Aluminate_Glass_Ionomer_Hybrid_Cement.html",
  "description": "A dental restoration material containing calcium aluminate, polyacrylic acid with basic ion-leachable glass particles as powder component with water as liquid component to complete the acid-base reaction of glass ionomer and hydration of calcium aluminate cement.",
  "term_id": "OHD:0001008",
  "term_label": "calcium aluminate glass ionomer hybrid cement dental restoration material",
  "category": "HYBRID",
  "curation_status": "STUB",
  "parents": [
   "Dental restoration material"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Calcium hydroxide cement",
  "slug": "Calcium_Hydroxide_Cement",
  "page_url": "../pages/materials/Calcium_Hydroxide_Cement.html",
  "description": "A dental restoration material that contains calcium hydroxide as a chief ingredient and is suspended in a solvent carrier with a thickening agent.",
  "term_id": "OHD:0001045",
  "term_label": "calcium hydroxide cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Dental restoration material"
  ],
  "children": [],
  "synonyms": [
   "calcium hydroxide liner",
   "hard-setting calcium hydroxide"
  ],
  "setting_mechanisms": [
   "SELF_CURED",
   "LIGHT_CURED"
  ],
  "use_contexts": [
   "LINER_OR_BASE",
   "PULP_THERAPY"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 2,
  "n_composition": 1,
  "n_properties": 0,
  "n_adverse_effects": 1,
  "fda_device_classes": [
   "CLASS_II"
  ],
  "fda_regulations": [
   "872.3250"
  ],
  "fda_product_codes": [],
  "fda_statuses": [
   "CLEARED"
  ]
 },
 {
  "name": "Ceramic",
  "slug": "Ceramic",
  "page_url": "../pages/materials/Ceramic.html",
  "description": "A dental restoration material that has a nonmetallic inorganic structure consisting primarily of compounds containing oxygen combined with one or more metallic or semi-metallic elements that are processed at high temperatures, pressed, and polished or milled.",
  "term_id": "OHD:0000135",
  "term_label": "ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Dental restoration material"
  ],
  "children": [
   "Glass matrix ceramic",
   "Polycrystalline ceramic",
   "Resin matrix ceramic"
  ],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Cobalt chromium metal",
  "slug": "Cobalt_Chromium_Metal",
  "page_url": "../pages/materials/Cobalt_Chromium_Metal.html",
  "description": "A predominantly base metal dental restoration material this is primarly composed of cobalt chromium.",
  "term_id": "OHD:0001083",
  "term_label": "cobalt chromium metal dental resotration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Predominantly base metal"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Commercially pure titanium",
  "slug": "Commercially_Pure_Titanium",
  "page_url": "../pages/materials/Commercially_Pure_Titanium.html",
  "description": "A titanium dental restoration material that contain pure titanium with minimum impurities.",
  "term_id": "OHD:0001086",
  "term_label": "commercially pure titanium dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Titanium"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Compomer resin-based composite",
  "slug": "Compomer_Resin-based_Composite",
  "page_url": "../pages/materials/Compomer_Resin-based_Composite.html",
  "description": "A resin-based composite dental restoration material that contains fluoride-releasing silicate glass filler phase and a methacrylate based matrix with carboxylic acid functional groups.",
  "term_id": "OHD:0001019",
  "term_label": "compomer resin-based composite dental restoration material",
  "category": "HYBRID",
  "curation_status": "STUB",
  "parents": [
   "Resin-based composite"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Dental restoration material",
  "slug": "Dental_Restoration_Material",
  "page_url": "../pages/materials/Dental_Restoration_Material.html",
  "description": "A processed material that bears a dental restoration material role.",
  "term_id": "OHD:0000000",
  "term_label": "dental restoration material",
  "category": "OTHER",
  "curation_status": "STUB",
  "parents": [],
  "children": [
   "Acid-base cement",
   "Calcium aluminate glass ionomer hybrid cement",
   "Calcium hydroxide cement",
   "Ceramic",
   "Hydroxyethyl methacrylate",
   "Metal",
   "Mineral trioxide aggregate cement",
   "Resin-based cement",
   "Resin-based composite"
  ],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Feldspathic glass matrix ceramic",
  "slug": "Feldspathic_Glass_Matrix_Ceramic",
  "page_url": "../pages/materials/Feldspathic_Glass_Matrix_Ceramic.html",
  "description": "A glass matrix ceramic dental restoration material that primarily contains a ternary material system composed of kaolin (hydrated aluminosilicate), silica, and naturally occurring feldspar (a mixture of potassium and sodium aluminosilicates).",
  "term_id": "OHD:0001051",
  "term_label": "feldspathic glass matrix ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Glass matrix ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Flowable resin-based composite",
  "slug": "Flowable_Resin-based_Composite",
  "page_url": "../pages/materials/Flowable_Resin-based_Composite.html",
  "description": "A resin-based composite dental restoration material that has low-viscosity and is recommended for cervical lesions, restorations in deciduous teeth, and other small, low- or non-stress bearing restorations.",
  "term_id": "OHD:0001012",
  "term_label": "flowable resin-based composite dental restoration material",
  "category": "RESIN_COMPOSITE",
  "curation_status": "STUB",
  "parents": [
   "Resin-based composite"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Fluorapatite based synthetic glass matrix ceramic",
  "slug": "Fluorapatite_Based_Synthetic_Glass_Matrix_Ceramic",
  "page_url": "../pages/materials/Fluorapatite_Based_Synthetic_Glass_Matrix_Ceramic.html",
  "description": "A synthetic glass matrix ceramic in which the glass phases may be combined with apatite crystals, in addition to leucite, for thermal expansion compatibility with metals and for improved strength.",
  "term_id": "OHD:0001055",
  "term_label": "fluorapatite based synthetic glass matrix ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Synthetic glass matrix ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Glass ionomer cement",
  "slug": "Glass_Ionomer_Cement",
  "page_url": "../pages/materials/Glass_Ionomer_Cement.html",
  "description": "An acid-base cement dental restoration material containing basic ion-leachable glass (fluoroaluminosilicate glass) as a powder component with polymeric water-soluble acid (polyacrylic acid, polyprotic carboxylic acid) as liquid component to complete the acid-base reaction.",
  "term_id": "OHD:0001006",
  "term_label": "glass ionomer cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Acid-base cement"
  ],
  "children": [],
  "synonyms": [
   "GIC",
   "glass-ionomer",
   "glass polyalkenoate cement"
  ],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [
   "DIRECT_RESTORATION",
   "LINER_OR_BASE",
   "LUTING"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 4,
  "n_composition": 3,
  "n_properties": 2,
  "n_adverse_effects": 0,
  "fda_device_classes": [
   "CLASS_II"
  ],
  "fda_regulations": [
   "872.3275"
  ],
  "fda_product_codes": [
   "EMA"
  ],
  "fda_statuses": [
   "CLEARED"
  ]
 },
 {
  "name": "Glass matrix ceramic",
  "slug": "Glass_Matrix_Ceramic",
  "page_url": "../pages/materials/Glass_Matrix_Ceramic.html",
  "description": "A ceramic dental restoration material that contains crystallized ceramic portions which are uniformally distributed within a glass phase.",
  "term_id": "OHD:0001032",
  "term_label": "glass matrix ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Ceramic"
  ],
  "children": [
   "Feldspathic glass matrix ceramic",
   "Synthetic glass matrix ceramic"
  ],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Gold foil",
  "slug": "Gold_Foil",
  "page_url": "../pages/materials/Gold_Foil.html",
  "description": "A metal dental restoration material in which the principal ingredient is gold.",
  "term_id": "OHD:0000034",
  "term_label": "gold foil dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Metal"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "COLD_WORKING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "High noble metal",
  "slug": "High_Noble_Metal",
  "page_url": "../pages/materials/High_Noble_Metal.html",
  "description": "A noble metal dental restoration material that is composed of a metallic alloy that contains 40% by weight or more of gold and 60% by weight or more noble metal elements.",
  "term_id": "OHD:0000147",
  "term_label": "high noble metal dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Noble metal"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Hydroxyethyl methacrylate",
  "slug": "Hydroxyethyl_Methacrylate",
  "page_url": "../pages/materials/Hydroxyethyl_Methacrylate.html",
  "description": "A dental restoration material which is a hydrophilic monomer used in dental adhesives, and primers.",
  "term_id": "OHD:0001082",
  "term_label": "hydroxyethyl methacrylate dental restoration material",
  "category": "ADHESIVE",
  "curation_status": "STUB",
  "parents": [
   "Dental restoration material"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Leucite based synthetic glass matrix ceramic",
  "slug": "Leucite_Based_Synthetic_Glass_Matrix_Ceramic",
  "page_url": "../pages/materials/Leucite_Based_Synthetic_Glass_Matrix_Ceramic.html",
  "description": "A synthetic glass matrix ceramic that contains a leucite (K2OAl2O34SiO2) crystalline phase dispersed in a glass matrix.",
  "term_id": "OHD:0001053",
  "term_label": "leucite based synthetic glass matrix ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Synthetic glass matrix ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Lithia based synthetic glass matrix ceramic",
  "slug": "Lithia_Based_Synthetic_Glass_Matrix_Ceramic",
  "page_url": "../pages/materials/Lithia_Based_Synthetic_Glass_Matrix_Ceramic.html",
  "description": "A synthetic glass matrix ceramic that contains a lithium disilicate system (SiO2-Li2O-K2O-ZnO-P2O5 Al2O3-[zirconium dioxide] ZrO2).",
  "term_id": "OHD:0001054",
  "term_label": "lithia based synthetic glass matrix ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Synthetic glass matrix ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Macrofilled resin-based composite",
  "slug": "Macrofilled_Resin-based_Composite",
  "page_url": "../pages/materials/Macrofilled_Resin-based_Composite.html",
  "description": "A resin-based composite dental restoration material that contains macrosize filler particles.",
  "term_id": "OHD:0001014",
  "term_label": "macrofilled resin-based composite dental restoration material",
  "category": "RESIN_COMPOSITE",
  "curation_status": "STUB",
  "parents": [
   "Resin-based composite"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Metal",
  "slug": "Metal",
  "page_url": "../pages/materials/Metal.html",
  "description": "A dental restoration material that consists mostly of metal and metal alloys.",
  "term_id": "OHD:0000048",
  "term_label": "metal dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Dental restoration material"
  ],
  "children": [
   "Amalgam",
   "Gold foil",
   "Noble metal",
   "Predominantly base metal",
   "Stainless steel",
   "Titanium"
  ],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Metal modified glass ionomer",
  "slug": "Metal_Modified_Glass_Ionomer",
  "page_url": "../pages/materials/Metal_Modified_Glass_Ionomer.html",
  "description": "An acid-base cement dental restoration material where in glass ionomer cements the glasses are fused with metals such as gold, silver, titanium, and silver to improve their strength.",
  "term_id": "OHD:0001020",
  "term_label": "metal modified glass ionomer dental restoration material",
  "category": "CEMENT",
  "curation_status": "STUB",
  "parents": [
   "Acid-base cement"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Microfilled resin-based composite",
  "slug": "Microfilled_Resin-based_Composite",
  "page_url": "../pages/materials/Microfilled_Resin-based_Composite.html",
  "description": "A resin-based composite dental restoration material which is composed of dimethacrylate resins with 0.04-m colloidal silica fillers and prepolymerized resins, which are sometimes filled with colloidal silica.",
  "term_id": "OHD:0001015",
  "term_label": "microfilled resin-based composite dental restoration material",
  "category": "RESIN_COMPOSITE",
  "curation_status": "STUB",
  "parents": [
   "Resin-based composite"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Mineral trioxide aggregate cement",
  "slug": "Mineral_Trioxide_Aggregate_Cement",
  "page_url": "../pages/materials/Mineral_Trioxide_Aggregate_Cement.html",
  "description": "A dental restoration material that primarily consists of tricalcium silicate, dicalcium silicate (similar to Portland cement), calcium aluminate, gypsum, radiopacifiers and set by hydration of silicates in the presence of moisture.",
  "term_id": "OHD:00001025",
  "term_label": "mineral trioxide aggregate cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Dental restoration material"
  ],
  "children": [],
  "synonyms": [
   "MTA",
   "mineral trioxide aggregate",
   "calcium silicate cement"
  ],
  "setting_mechanisms": [
   "HYDRATION"
  ],
  "use_contexts": [
   "ENDODONTIC",
   "PULP_THERAPY"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 3,
  "n_composition": 4,
  "n_properties": 1,
  "n_adverse_effects": 1,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": [
   "UNKNOWN"
  ]
 },
 {
  "name": "Multichromatic zirconia ceramic",
  "slug": "Multichromatic_Zirconia_Ceramic",
  "page_url": "../pages/materials/Multichromatic_Zirconia_Ceramic.html",
  "description": "A zirconia polycrystalline ceramic dental restoration material that contains additions of layers of different pigments to provide a graded shade between the cervical and the incisal portion of the restoration to mimic the natural tooth appearance.",
  "term_id": "OHD:0001038",
  "term_label": "multichromatic zirconia ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Zirconia polycrystalline ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Multilayered zirconia ceramic",
  "slug": "Multilayered_Zirconia_Ceramic",
  "page_url": "../pages/materials/Multilayered_Zirconia_Ceramic.html",
  "description": "A zirconia polycrystalline ceramic dental restoration material that contains layered structure composed of different compositions of dental zirconias to provide graded structures that mimic not only the shade, but the translucency and esthetic appearance of natural teeth.",
  "term_id": "OHD:0001039",
  "term_label": "multilayered zirconia ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Zirconia polycrystalline ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Nano filled resin-based composite",
  "slug": "Nano_Filled_Resin-based_Composite",
  "page_url": "../pages/materials/Nano_Filled_Resin-based_Composite.html",
  "description": "A resin-based composite dental restoration material that contains nanometer-sized filler particles (1 to 100 nm) throughout the resin matrix.",
  "term_id": "OHD:0001017",
  "term_label": "nano filled resin-based composite dental restoration material",
  "category": "RESIN_COMPOSITE",
  "curation_status": "STUB",
  "parents": [
   "Resin-based composite"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Nano hybrid resin-based composite",
  "slug": "Nano_Hybrid_Resin-based_Composite",
  "page_url": "../pages/materials/Nano_Hybrid_Resin-based_Composite.html",
  "description": "A resin-based composite dental restoration material which consist of large particles (0.4 to 5 m) with added nanometer-sized filler particles. Thus they are hybrid materials, not true nanofilled composites.",
  "term_id": "OHD:0001018",
  "term_label": "nano hybrid resin-based composite dental restoration material",
  "category": "RESIN_COMPOSITE",
  "curation_status": "STUB",
  "parents": [
   "Resin-based composite"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Nickel chromium metal",
  "slug": "Nickel_Chromium_Metal",
  "page_url": "../pages/materials/Nickel_Chromium_Metal.html",
  "description": "A predominantly base metal dental restoration material that is primarily composed of nickel chromium.",
  "term_id": "OHD:0001084",
  "term_label": "nickel chromium metal dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Predominantly base metal"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Noble metal",
  "slug": "Noble_Metal",
  "page_url": "../pages/materials/Noble_Metal.html",
  "description": "A metal dental restoration material that is composed of a metallic alloy that contains 25% or more (by weight) of noble metal elements.",
  "term_id": "OHD:0000146",
  "term_label": "noble metal dental restoration material",
  "category": "METAL",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Metal"
  ],
  "children": [
   "High noble metal",
   "Silver-palladium alloy metal"
  ],
  "synonyms": [
   "noble metal alloy",
   "noble alloy"
  ],
  "setting_mechanisms": [
   "CASTING",
   "MILLING"
  ],
  "use_contexts": [
   "INDIRECT_RESTORATION"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 4,
  "n_composition": 4,
  "n_properties": 0,
  "n_adverse_effects": 1,
  "fda_device_classes": [
   "CLASS_II"
  ],
  "fda_regulations": [
   "872.3060"
  ],
  "fda_product_codes": [
   "EJS",
   "EJT"
  ],
  "fda_statuses": [
   "EXEMPT"
  ]
 },
 {
  "name": "Polycrystalline ceramic",
  "slug": "Polycrystalline_Ceramic",
  "page_url": "../pages/materials/Polycrystalline_Ceramic.html",
  "description": "A ceramic dental restoration material that contains small crystals, also known as grains, that are separated by grain boundaries and present a random crystallographic orientation , that do not contain a glass phase.",
  "term_id": "OHD:0001033",
  "term_label": "polycrystalline ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Ceramic"
  ],
  "children": [
   "Polycrystalline composite ceramic",
   "Zirconia polycrystalline ceramic"
  ],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Polycrystalline composite ceramic",
  "slug": "Polycrystalline_Composite_Ceramic",
  "page_url": "../pages/materials/Polycrystalline_Composite_Ceramic.html",
  "description": "A polycrystalline ceramic dental restoration material that combines different cryatalline phases to improve specific properties.",
  "term_id": "OHD:0001040",
  "term_label": "polycrystalline composite ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Polycrystalline ceramic"
  ],
  "children": [
   "Alumina toughened zirconia ceramic",
   "Zirconia toughened alumina ceramic"
  ],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Predominantly base metal",
  "slug": "Predominantly_Base_Metal",
  "page_url": "../pages/materials/Predominantly_Base_Metal.html",
  "description": "A metal dental restoration material that is composed of group of cast metals that rely on Chromium for corrosion resistance.",
  "term_id": "OHD:0000156",
  "term_label": "predominantly base metal dental restoration material",
  "category": "METAL",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Metal"
  ],
  "children": [
   "Cobalt chromium metal",
   "Nickel chromium metal"
  ],
  "synonyms": [
   "base metal alloy",
   "non-precious alloy"
  ],
  "setting_mechanisms": [
   "CASTING",
   "MILLING",
   "ADDITIVE_MANUFACTURING"
  ],
  "use_contexts": [
   "INDIRECT_RESTORATION",
   "PROSTHODONTIC"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 4,
  "n_composition": 3,
  "n_properties": 0,
  "n_adverse_effects": 2,
  "fda_device_classes": [
   "CLASS_II"
  ],
  "fda_regulations": [
   "872.3710"
  ],
  "fda_product_codes": [
   "EJH"
  ],
  "fda_statuses": [
   "EXEMPT"
  ]
 },
 {
  "name": "Resin-based cement",
  "slug": "Resin-based_Cement",
  "page_url": "../pages/materials/Resin-based_Cement.html",
  "description": "A dental restoration material that contains methacrylate monomers, fillers and activator initiator system to facilitate light activated and/or chemically activated polymerization reactions.",
  "term_id": "OHD:0001005",
  "term_label": "resin-based cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "STUB",
  "parents": [
   "Dental restoration material"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Resin-based composite",
  "slug": "Resin-based_Composite",
  "page_url": "../pages/materials/Resin-based_Composite.html",
  "description": "A dental restoration material that is primarily composed of highly cross-linked organic polymeric matrix reinforced by filler particles and/or short fibers bound to the matrix by coupling agents and set by light and or chemically activated polymerization reaction.",
  "term_id": "OHD:0000036",
  "term_label": "resin-based composite dental restoration material",
  "category": "RESIN_COMPOSITE",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Dental restoration material"
  ],
  "children": [
   "Bulk-filled resin-based composite",
   "Compomer resin-based composite",
   "Flowable resin-based composite",
   "Macrofilled resin-based composite",
   "Microfilled resin-based composite",
   "Nano filled resin-based composite",
   "Nano hybrid resin-based composite"
  ],
  "synonyms": [
   "composite resin",
   "dental composite",
   "tooth-colored filling",
   "white filling"
  ],
  "setting_mechanisms": [
   "LIGHT_CURED",
   "SELF_CURED",
   "DUAL_CURED"
  ],
  "use_contexts": [
   "DIRECT_RESTORATION",
   "INDIRECT_RESTORATION"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 8,
  "n_composition": 5,
  "n_properties": 1,
  "n_adverse_effects": 1,
  "fda_device_classes": [
   "CLASS_II"
  ],
  "fda_regulations": [
   "872.3690"
  ],
  "fda_product_codes": [
   "EBF",
   "OFW"
  ],
  "fda_statuses": [
   "CLEARED"
  ]
 },
 {
  "name": "Resin-modified glass ionomer",
  "slug": "Resin-modified_Glass_Ionomer",
  "page_url": "../pages/materials/Resin-modified_Glass_Ionomer.html",
  "description": "An acid-base cement dental restoration material with modification of glass ionomer cement with some monomer component and associated activator initiator system to facilitate light and chemically activated polymerization reaction.",
  "term_id": "OHD:0001026",
  "term_label": "resin-modified glass ionomer dental restoration material",
  "category": "HYBRID",
  "curation_status": "STUB",
  "parents": [
   "Acid-base cement"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Resin matrix ceramic",
  "slug": "Resin_Matrix_Ceramic",
  "page_url": "../pages/materials/Resin_Matrix_Ceramic.html",
  "description": "A ceramic dental restoration material that consists of a ceramic network infiltrated with a polymer resin to integrate the mechanical properties of ceramics with the improved elasticity of resins.",
  "term_id": "OHD:0001047",
  "term_label": "resin matrix ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Ceramic"
  ],
  "children": [
   "Resin matrix glass ceramic",
   "Resin matrix zirconia silica ceramic",
   "Resin nano ceramic"
  ],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Resin matrix glass ceramic",
  "slug": "Resin_Matrix_Glass_Ceramic",
  "page_url": "../pages/materials/Resin_Matrix_Glass_Ceramic.html",
  "description": "A resin matrix ceramic dental restoration material that contains either lithium disilicate or leucite-reinforced glass ceramic filler, typically to improve esthetics, strength, and wear resistance.",
  "term_id": "OHD:0001049",
  "term_label": "resin matrix glass ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Resin matrix ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Resin matrix zirconia silica ceramic",
  "slug": "Resin_Matrix_Zirconia_Silica_Ceramic",
  "page_url": "../pages/materials/Resin_Matrix_Zirconia_Silica_Ceramic.html",
  "description": "A resin matrix ceramic dental restoration material that contains zirconia or silica based ceramic filler, typically to improve esthetics, strength, and wear resistance.",
  "term_id": "OHD:0001050",
  "term_label": "resin matrix zirconia silica ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Resin matrix ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Resin nano ceramic",
  "slug": "Resin_Nano_Ceramic",
  "page_url": "../pages/materials/Resin_Nano_Ceramic.html",
  "description": "A resin matrix ceramic dental restoration material that contains nano ceramic filler, typically to improve esthetics, strength, and wear resistance.",
  "term_id": "OHD:0001048",
  "term_label": "resin nano ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Resin matrix ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Silver-palladium alloy metal",
  "slug": "Silver-palladium_Alloy_Metal",
  "page_url": "../pages/materials/Silver-palladium_Alloy_Metal.html",
  "description": "A noble metal dental restoration material that is composed of predominantly silver in composition and at least 25% by weight of palladium to provide nobility of the alloy.",
  "term_id": "OHD:0001085",
  "term_label": "silver-palladium alloy metal dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Noble metal"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Stainless steel",
  "slug": "Stainless_Steel",
  "page_url": "../pages/materials/Stainless_Steel.html",
  "description": "A metal dental restoration material in which the principal ingredient is stainless steel.",
  "term_id": "OHD:0000137",
  "term_label": "stainless steel dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Metal"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Synthetic glass matrix ceramic",
  "slug": "Synthetic_Glass_Matrix_Ceramic",
  "page_url": "../pages/materials/Synthetic_Glass_Matrix_Ceramic.html",
  "description": "A glass matrix ceramic dental restoration material that contains synthetic materials which varies among manufacturers, but commonly includes silicon dioxide (SiO2), potassium oxide (K2O), sodium oxide (Na2O), and aluminum oxide (Al2O3).",
  "term_id": "OHD:0001052",
  "term_label": "synthetic glass matrix ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Glass matrix ceramic"
  ],
  "children": [
   "Fluorapatite based synthetic glass matrix ceramic",
   "Leucite based synthetic glass matrix ceramic",
   "Lithia based synthetic glass matrix ceramic"
  ],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Titanium",
  "slug": "Titanium",
  "page_url": "../pages/materials/Titanium.html",
  "description": "A metal dental restoration material that contains 85% or more titanium.",
  "term_id": "OHD:0000136",
  "term_label": "titanium dental restoration material",
  "category": "METAL",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Metal"
  ],
  "children": [
   "Commercially pure titanium",
   "Titanium alloy"
  ],
  "synonyms": [
   "titanium and titanium alloys"
  ],
  "setting_mechanisms": [
   "MILLING",
   "CASTING",
   "ADDITIVE_MANUFACTURING"
  ],
  "use_contexts": [
   "IMPLANT",
   "INDIRECT_RESTORATION"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 3,
  "n_composition": 1,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [
   "CLASS_II"
  ],
  "fda_regulations": [
   "872.3640"
  ],
  "fda_product_codes": [
   "DZE",
   "NRQ",
   "OAT"
  ],
  "fda_statuses": [
   "CLEARED"
  ]
 },
 {
  "name": "Titanium alloy",
  "slug": "Titanium_Alloy",
  "page_url": "../pages/materials/Titanium_Alloy.html",
  "description": "A titanium dental restoration material that contains titanium with incorporation of alpha or beta microstructural stabilizers. Common microstructural stabilizers include aluminum, vanadium, niobium, cobalt, copper, nickel, or molybdenum.",
  "term_id": "OHD:0001087",
  "term_label": "titanium alloy dental restoration material",
  "category": "METAL",
  "curation_status": "STUB",
  "parents": [
   "Titanium"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Zinc oxide cement",
  "slug": "Zinc_Oxide_Cement",
  "page_url": "../pages/materials/Zinc_Oxide_Cement.html",
  "description": "An acid-base cement dental restoration material containing zinc-oxide as a powder component with some specific liquid component to complete the acid-base reaction.",
  "term_id": "OHD:0001022",
  "term_label": "zinc oxide cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "STUB",
  "parents": [
   "Acid-base cement"
  ],
  "children": [
   "Zinc oxide eugenol cement",
   "Zinc oxide non-eugenol cement"
  ],
  "synonyms": [],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Zinc oxide eugenol cement",
  "slug": "Zinc_Oxide_Eugenol_Cement",
  "page_url": "../pages/materials/Zinc_Oxide_Eugenol_Cement.html",
  "description": "A zinc-oxide cement dental restoration material containing eugenol as a liquid component to complete the acid-base reaction.",
  "term_id": "OHD:0001007",
  "term_label": "zinc oxide eugenol cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Zinc oxide cement"
  ],
  "children": [],
  "synonyms": [
   "ZOE",
   "zinc oxide-eugenol"
  ],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [
   "LINER_OR_BASE",
   "LUTING",
   "TEMPORARY"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 4,
  "n_composition": 2,
  "n_properties": 2,
  "n_adverse_effects": 0,
  "fda_device_classes": [
   "CLASS_I"
  ],
  "fda_regulations": [
   "872.3275"
  ],
  "fda_product_codes": [
   "EMB"
  ],
  "fda_statuses": [
   "EXEMPT"
  ]
 },
 {
  "name": "Zinc oxide non-eugenol cement",
  "slug": "Zinc_Oxide_Non-eugenol_Cement",
  "page_url": "../pages/materials/Zinc_Oxide_Non-eugenol_Cement.html",
  "description": "A zinc-oxide cement dental restoration material containing aliphatic acid or butyric acid to substitute the eugenol as a liquid component to complete the acid-base reaction.",
  "term_id": "OHD:0001010",
  "term_label": "zinc oxide non-eugenol cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "STUB",
  "parents": [
   "Zinc oxide cement"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Zinc phosphate cement",
  "slug": "Zinc_Phosphate_Cement",
  "page_url": "../pages/materials/Zinc_Phosphate_Cement.html",
  "description": "An acid-base cement dental restoration material containing zinc-oxide and magnesium oxide as a powder component with phosphoric acid as liquid component to complete the acid-base reaction.",
  "term_id": "OHD:0001042",
  "term_label": "zinc phosphate cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "STUB",
  "parents": [
   "Acid-base cement"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Zinc polycarboxylate cement",
  "slug": "Zinc_Polycarboxylate_Cement",
  "page_url": "../pages/materials/Zinc_Polycarboxylate_Cement.html",
  "description": "An acid-base cement dental restoration material containing zinc-oxide and magnesium oxide as a powder component with polyacrylic acid and water as liquid component to complete the acid-base reaction.",
  "term_id": "OHD:0001043",
  "term_label": "zinc polycarboxylate cement dental restoration material",
  "category": "CEMENT",
  "curation_status": "STUB",
  "parents": [
   "Acid-base cement"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "ACID_BASE_REACTION"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 },
 {
  "name": "Zirconia polycrystalline ceramic",
  "slug": "Zirconia_Polycrystalline_Ceramic",
  "page_url": "../pages/materials/Zirconia_Polycrystalline_Ceramic.html",
  "description": "A polycrystalline ceramic dental restoration material that contains Zirconia which is partially stabilized zirconium oxide usually in the tetragonal phase.",
  "term_id": "OHD:0001034",
  "term_label": "zirconia polycrystalline ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "IN_PROGRESS",
  "parents": [
   "Polycrystalline ceramic"
  ],
  "children": [
   "3Y-TZP zirconia ceramic",
   "4Y-PSZ zirconia ceramic",
   "5Y-PSZ zirconia ceramic",
   "Multichromatic zirconia ceramic",
   "Multilayered zirconia ceramic"
  ],
  "synonyms": [
   "zirconia",
   "yttria-stabilized zirconia",
   "YSZ"
  ],
  "setting_mechanisms": [
   "MILLING",
   "SINTERING"
  ],
  "use_contexts": [
   "IMPLANT",
   "INDIRECT_RESTORATION"
  ],
  "agencies": [
   "FDA"
  ],
  "n_products": 0,
  "n_evidence": 2,
  "n_composition": 2,
  "n_properties": 1,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": [
   "UNKNOWN"
  ]
 },
 {
  "name": "Zirconia toughened alumina ceramic",
  "slug": "Zirconia_Toughened_Alumina_Ceramic",
  "page_url": "../pages/materials/Zirconia_Toughened_Alumina_Ceramic.html",
  "description": "A polycrystalline composite ceramic dental restoration material that combines zirconium to increase the material's mechanical and esthetic properties.",
  "term_id": "OHD:0001041",
  "term_label": "zirconia toughened alumina ceramic dental restoration material",
  "category": "CERAMIC",
  "curation_status": "STUB",
  "parents": [
   "Polycrystalline composite ceramic"
  ],
  "children": [],
  "synonyms": [],
  "setting_mechanisms": [
   "SINTERING",
   "MILLING"
  ],
  "use_contexts": [],
  "agencies": [],
  "n_products": 0,
  "n_evidence": 0,
  "n_composition": 0,
  "n_properties": 0,
  "n_adverse_effects": 0,
  "fda_device_classes": [],
  "fda_regulations": [],
  "fda_product_codes": [],
  "fda_statuses": []
 }
];
