"""Browser data export: one flat record per material for app/index.html."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from dentmatmech.yaml_io import APP_DIR, load_kb, slugify


def _fda(data: dict[str, Any]) -> dict[str, Any]:
    """Summarize the FDA regulatory entries for faceting."""
    classes: list[str] = []
    regs: list[str] = []
    codes: list[str] = []
    statuses: list[str] = []
    for rs in data.get("regulatory_status", []) or []:
        if rs.get("agency") != "FDA":
            continue
        if rs.get("device_class"):
            classes.append(rs["device_class"])
        if rs.get("regulation_number"):
            regs.append(rs["regulation_number"])
        codes.extend(rs.get("product_codes", []) or [])
        if rs.get("status"):
            statuses.append(rs["status"])
    return {
        "fda_device_classes": sorted(set(classes)),
        "fda_regulations": sorted(set(regs)),
        "fda_product_codes": sorted(set(codes)),
        "fda_statuses": sorted(set(statuses)),
    }


def _count_evidence(node: Any) -> int:
    if isinstance(node, dict):
        n = len(node.get("evidence", []) or []) if "evidence" in node else 0
        return n + sum(_count_evidence(v) for k, v in node.items() if k != "evidence")
    if isinstance(node, list):
        return sum(_count_evidence(v) for v in node)
    return 0


def build_records(kb: dict[str, dict[str, Any]] | None = None) -> list[dict[str, Any]]:
    kb = kb if kb is not None else load_kb()
    children: dict[str, list[str]] = {}
    for name, data in kb.items():
        for parent in data.get("parents", []) or []:
            children.setdefault(parent, []).append(name)
    records = []
    for name, data in kb.items():
        term = data.get("material_term", {}).get("term", {})
        rec = {
            "name": name,
            "slug": slugify(name),
            "page_url": f"../pages/materials/{slugify(name)}.html",
            "description": data.get("description", ""),
            "term_id": term.get("id", ""),
            "term_label": term.get("label", ""),
            "category": data.get("category", ""),
            "curation_status": data.get("curation_status", "STUB"),
            "parents": data.get("parents", []) or [],
            "children": sorted(children.get(name, [])),
            "synonyms": data.get("synonyms", []) or [],
            "setting_mechanisms": data.get("setting_mechanisms", []) or [],
            "use_contexts": sorted({u.get("use_context") for u in data.get("clinical_uses", []) or [] if u.get("use_context")}),
            "agencies": sorted({r.get("agency") for r in data.get("regulatory_status", []) or [] if r.get("agency")}),
            "n_products": len(data.get("products", []) or []),
            "n_evidence": _count_evidence(data),
            "n_composition": len(data.get("composition", []) or []),
            "n_properties": len(data.get("properties", []) or []),
            "n_adverse_effects": len(data.get("adverse_effects", []) or []),
        }
        rec.update(_fda(data))
        records.append(rec)
    return records


def export_browser_data(out: Path = APP_DIR / "data.js") -> int:
    records = build_records()
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(records, indent=1, ensure_ascii=False)
    out.write_text(f"// Generated by `dentmatmech export-browser`; do not edit.\nwindow.DENTMATMECH_DATA = {payload};\n", encoding="utf-8")
    return len(records)
